### PR TITLE
Document property active of settings object

### PR DESCRIPTION
**Pull request by maxhallinan**
This documents user customization of the class applied to activated elements.

### CODE REVIEW

**Comment by corysimmons** [comment]
Cool, I like this. Is there anyway we could update this to accept _any_ selector instead of just classes?

**Comment by maxhallinan** [comment]
The value of `selector.active` could be given to any html attribute as long as that string constitutes an [acceptable attribute value](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2). And nothing technically prevents us from setting invalid values. If you want to enable the user to choose which attribute is set when the element enters the active range, you could refactor along these lines: `settings.activeAttrName` and `settings.activeAttrValue` and set like this to activate: `$(v).attr(settings.activeAttrName, settings.activeAttrValue);` and like this to deactivate:`$(v).attr(settings.activeAttrName, '');` But if `$('.element').length > 1`, you run the risk that someone will set the same id on multiple elements. 

What's the use case for this idea? If you want to offer users more capability in general, it might be better to continue applying `settings.active` as a class and accept callbacks that are executed when the element is activated and deactivated. The user could set other attribute values within those callbacks and do anything else they desired. This affords much more capability to the user while keeping the plugin itself relatively simple.

**Comment by corysimmons** [comment]
Alright, makes sense. Forget the selector thing -- classes are better anyway.

I'm pretty bad at JS and you're pretty good at it. Care to add the callback functionality and submit a PR?

**Comment by maxhallinan** [comment]
Hey Cory, sorry to take so long getting back to you. I'm in the middle of another project. I'd be happy to add this feature, though I don't share you're opinion that you're "pretty bad" at JS. When I have some free time in the upcoming week, I'll put this together.

**Comment by corysimmons** [comment]
:+1:

**Pull request merged**
